services:
  - type: static_site
    name: reservationform
    branch: main
    buildCommand: sh ./build-render-static.sh
    staticPublishPath: dist
    envVars:
      - key: WHATSAPP_NUMBER
        sync: false
